apiVersion: v1
kind: Service
metadata:
  name: kafka-ui
  namespace: secret-scan
spec:
  selector:
    app: kafka-ui
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8080
  type: ClusterIP  # Or use LoadBalancer / NodePort based on setup
