apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-server
  namespace: secret-scan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook-server
  template:
    metadata:
      labels:
        app: webhook-server
    spec:
      containers:
      - name: webhook
        image: jatin560/webhook-server:v6
        ports:
        - containerPort: 8080

